# Generated by Django 3.2.4 on 2021-10-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_applied',
        ),
    ]
