# Generated by Django 3.2.4 on 2021-10-16 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_job_is_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=300)),
                ('university_name', models.CharField(max_length=100)),
                ('university_location', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('degree_duration', models.DurationField()),
                ('school_name', models.CharField(max_length=200)),
                ('school_location', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('class_duration', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
