# Generated by Django 3.2.4 on 2021-10-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_create_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_resume',
        ),
    ]
