# Generated by Django 3.2.4 on 2021-10-16 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, null=True)),
                ('expertise', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('project_duration', models.DurationField()),
                ('project_ongoing', models.BooleanField(default=False)),
                ('project_desc', models.TextField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masters_university_name', models.CharField(max_length=100, null=True)),
                ('masters_university_location', models.CharField(max_length=200, null=True)),
                ('masters_degree', models.CharField(max_length=100, null=True)),
                ('masters_branch', models.CharField(max_length=200, null=True)),
                ('masters_degree_duration', models.DurationField()),
                ('master_pursuing', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('intern_position', models.CharField(max_length=200, null=True)),
                ('interniship_duration', models.DurationField()),
                ('inter_here', models.BooleanField(default=False)),
                ('internship_location', models.CharField(max_length=200, null=True)),
                ('internship_desc', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='High_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, null=True)),
                ('school_location', models.CharField(max_length=200, null=True)),
                ('class_name', models.CharField(max_length=200, null=True)),
                ('branch', models.CharField(max_length=200, null=True)),
                ('class_duration', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('job_position', models.CharField(max_length=200, null=True)),
                ('job_location', models.CharField(max_length=200, null=True)),
                ('job_duration', models.DurationField()),
                ('working_here', models.BooleanField(default=False)),
                ('job_desc', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=200, null=True)),
                ('certification_company', models.CharField(max_length=200, null=True)),
                ('certification_duration', models.DurationField()),
                ('certification_ongoing', models.BooleanField(default=False)),
                ('certification_desc', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bachelors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bachelors_university_name', models.CharField(max_length=100, null=True)),
                ('bachelors_university_location', models.CharField(max_length=200, null=True)),
                ('bachelors_degree', models.CharField(max_length=100, null=True)),
                ('bachelors_branch', models.CharField(max_length=200, null=True)),
                ('bachelors_degree_duration', models.DurationField()),
                ('bachelors_pursuing', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
