# Generated by Django 3.2.4 on 2021-10-17 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_resume', '0002_rename_company_name_internship_inter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=200, null=True)),
                ('duration', models.DurationField()),
                ('ongoing', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='high_school',
            name='user',
        ),
        migrations.RemoveField(
            model_name='masters',
            name='user',
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='certification_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='certification_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='certification_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='certification_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='certification_ongoing',
            new_name='ongoing',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='company_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_location',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='working_here',
            new_name='ongoing',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='interniship_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='inter_company_name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='intern_position',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='inter_here',
            new_name='ongoing',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_location',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_ongoing',
            new_name='ongoing',
        ),
        migrations.DeleteModel(
            name='Bachelors',
        ),
        migrations.DeleteModel(
            name='High_school',
        ),
        migrations.DeleteModel(
            name='Masters',
        ),
    ]
