# Generated by Django 3.2.4 on 2021-10-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0003_auto_20211017_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='qualifications',
            name='ongoing',
        ),
        migrations.AlterField(
            model_name='certifications',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
